[package]
name = "rs"
version = "0.1.0"
edition = "2024"

[dependencies]
js-sys       = "0.3"
wasm-bindgen = "0.2"

[lib]
# crate-type = ["cdylib", "rlib"]
crate-type = ["cdylib"]

[profile.release]
# opt-level = 3
lto = true
